# Generated by Django 5.1.5 on 2025-02-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_Management', '0005_rename_task_name_todotask_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='user',
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('reminder', 'Reminder'), ('deadline', 'Deadline'), ('alert', 'Alert')], max_length=50),
        ),
    ]
