# Generated by Django 5.1.5 on 2025-02-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_Management', '0006_remove_alert_user_alter_alert_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='trigger_date',
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
