# Generated by Django 5.1.5 on 2025-02-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_Management', '0007_remove_alert_trigger_date_alter_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='trigger_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
