# Generated by Django 5.1.5 on 2025-02-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_Management', '0009_alerts_delete_alert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alerts',
        ),
        migrations.RemoveField(
            model_name='goalstep',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='exammarks',
            name='preparation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='GoalStep',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
